buildscript {
	repositories {
		gradlePluginPortal()
		flatDir {
			dirs 'libs'
		}
		dependencies {
			classpath name:'package-compileonly-sdk', version: '1.5.0'
			classpath "gradle.plugin.com.github.johnrengelman:shadow:7.1.1"
		}
	}
}

plugins {
	id 'java'
}

configure(allprojects){

	apply plugin: 'com.github.johnrengelman.shadow'
	apply plugin: "com.automationanywhere.command-codegen"

	ext {
		groupName = 'com.automationanywhere'
		testNgVersion = '7.11.0'
		loggerVersion = '2.25.2'
		jnaVersion = '5.3.1'
		version '3.5.2'
	}
	group "$groupName"

	sourceCompatibility = JavaVersion.VERSION_11

	compileJava.options.encoding = 'UTF-8'
	compileTestJava.options.encoding = 'UTF-8'

	repositories {
		mavenCentral()
		flatDir {
			dirs 'libs'
		}
	}

	packageJson{
		artifactName = project.name
		group = "$groupName"
		author = "Sumit Kumar"
		generatePackageWithDateTime = false
	}

	jar.dependsOn commandCodeGen

	shadowJar {
		archiveBaseName = project.name
		classifier = null
		mergeServiceFiles('META-INF/spring.*')
		mergeServiceFiles('META-INF/services/java.sql.Driver')
		zip64 = true
		exclude 'META-INF/MANIFEST.MF'
		exclude 'META-INF/*.SF'
		exclude 'META-INF/*.DSA'
		exclude 'META-INF/*.RSA'
		relocate 'org.apache.commons.io', 'botframework.shaded.commons.io'
	}

	dependencies {
		annotationProcessor name: 'package-compileonly-sdk', version: '1.5.0'
		compileOnly name: 'package-compileonly-sdk', version: '1.5.0'

		implementation name: 'package-runtime-sdk', version: '1.0.0'
		testImplementation name: 'package-compileonly-sdk', version: '1.5.0'
		testImplementation group: "org.testng", name:"testng", version: "$testNgVersion"

		testImplementation 'com.google.protobuf:protobuf-java:4.32.1' //table,record type use this internally

		// https://mvnrepository.com/artifact/org.json/json
		implementation 'org.json:json:20250517'

		// https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
		implementation group: "org.apache.logging.log4j", name: "log4j-api", version: "$loggerVersion"
		// https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
		implementation group: "org.apache.logging.log4j", name: "log4j-core", version: "$loggerVersion"

		// https://mvnrepository.com/artifact/commons-io/commons-io
		implementation 'commons-io:commons-io:2.20.0'
		// https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml
		implementation 'org.apache.poi:poi-ooxml:5.4.1'

		// https://mvnrepository.com/artifact/org.apache.commons/commons-csv
		implementation 'org.apache.commons:commons-csv:1.14.1'
	}

}
